package airlinebooking.core.ws.model;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Parameter;
import org.hibernate.annotations.Type;

import airlinebooking.core.ws.enumtype.ActiveType;

/**
 * AppParam generated by hbm2java
 */
@Entity
@Table(name = "app_param", catalog = "airlinebooking")
public class AppParam implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = -258598660342742829L;
	private Integer id;
	private String codeType;
	private String value;
	private String description;
	private ActiveType status = ActiveType.ACTIVE;
	private String telephone;
	private String attr1;
	private String attr2;
	private String attr3;
	private String attr4;
	private String createUser;
	private Date createDate;
	private String updateUser;
	private Date updateDate;

	public AppParam() {
	}

	public AppParam(String codeType) {
		this.codeType = codeType;
	}

	public AppParam(String codeType, String value, String description,
			ActiveType status, String telephone, String attr1, String attr2,
			String attr3, String attr4, String createUser, Date createDate,
			String updateUser, Date updateDate) {
		this.codeType = codeType;
		this.value = value;
		this.description = description;
		this.status = status;
		this.telephone = telephone;
		this.attr1 = attr1;
		this.attr2 = attr2;
		this.attr3 = attr3;
		this.attr4 = attr4;
		this.createUser = createUser;
		this.createDate = createDate;
		this.updateUser = updateUser;
		this.updateDate = updateDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "code_type", nullable = false, length = 100)
	public String getCodeType() {
		return this.codeType;
	}

	public void setCodeType(String codeType) {
		this.codeType = codeType;
	}

	@Column(name = "value", length = 65535)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "status")
	@Type(type = "airlinebooking.core.ws.enumtype.GenericEnumUserType", parameters = {
			@Parameter(name = "enumClass", value = "airlinebooking.core.ws.enumtype.ActiveType"),
			@Parameter(name = "identifierMethod", value = "getValue"),
			@Parameter(name = "valueOfMethod", value = "parseValue") })
	public ActiveType getStatus() {
		return this.status;
	}

	public void setStatus(ActiveType status) {
		this.status = status;
	}

	@Column(name = "telephone", length = 20)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "attr1", length = 100)
	public String getAttr1() {
		return this.attr1;
	}

	public void setAttr1(String attr1) {
		this.attr1 = attr1;
	}

	@Column(name = "attr2", length = 100)
	public String getAttr2() {
		return this.attr2;
	}

	public void setAttr2(String attr2) {
		this.attr2 = attr2;
	}

	@Column(name = "attr3", length = 100)
	public String getAttr3() {
		return this.attr3;
	}

	public void setAttr3(String attr3) {
		this.attr3 = attr3;
	}

	@Column(name = "attr4", length = 100)
	public String getAttr4() {
		return this.attr4;
	}

	public void setAttr4(String attr4) {
		this.attr4 = attr4;
	}

	@Column(name = "create_user", length = 100)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "update_user", length = 100)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
