package airlinebooking.core.ws.model;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Package generated by hbm2java
 */
@Entity
@Table(name = "customer_package")
public class CustomerPackage implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = -805497385346886132L;
	private Integer id;
	private Integer airlineType;
	private Integer weight;
	private Integer amount;
	private String createUser;
	private Date createDate;
	private String updateUser;
	private Date updateDate;

	public CustomerPackage() {
	}

	public CustomerPackage(Integer airlineType, Integer weight, Integer amount,
			String createUser, Date createDate, String updateUser,
			Date updateDate) {
		this.airlineType = airlineType;
		this.weight = weight;
		this.amount = amount;
		this.createUser = createUser;
		this.createDate = createDate;
		this.updateUser = updateUser;
		this.updateDate = updateDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "airline_type")
	public Integer getAirlineType() {
		return this.airlineType;
	}

	public void setAirlineType(Integer airlineType) {
		this.airlineType = airlineType;
	}

	@Column(name = "weight")
	public Integer getWeight() {
		return this.weight;
	}

	public void setWeight(Integer weight) {
		this.weight = weight;
	}

	@Column(name = "amount")
	public Integer getAmount() {
		return this.amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	@Column(name = "create_user", length = 100)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19, columnDefinition="TIMESTAMP default CURRENT_TIMESTAMP", insertable=false, updatable=false)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "update_user", length = 100)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 19, columnDefinition="TIMESTAMP default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP")
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
