package airlinebooking.core.ws.model;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Parameter;
import org.hibernate.annotations.Type;

import airlinebooking.core.ws.enumtype.AirlineType;

/**
 * TicketStorage generated by hbm2java
 */
@Entity
@Table(name = "ticket", catalog = "airlinebooking")
public class Ticket implements java.io.Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1927781322548261468L;
	private Integer id;
	private AirlineType airlineType;
	private String flightCode;
	private String originCode;
	private String destinationCode;
	private Date fromDate;
	private Date toDate;
	private Date fromTime;
	private Date toTime;
	private Integer durationTime;
	private String createUser;
	private Date createDate;
	private String updateUser;
	private Date updateDate;

	public Ticket() {
	}

	public Ticket(String flightCode,
			String originCode, String destinationCode, Date fromDate,
			Date toDate, Date fromTime, Date toTime, Integer durationTime, String createUser,
			Date createDate, String updateUser, Date updateDate) {
		this.flightCode = flightCode;
		this.originCode = originCode;
		this.destinationCode = destinationCode;
		this.fromDate = fromDate;
		this.toDate = toDate;
		this.fromTime = fromTime;
		this.toTime = toTime;
		this.durationTime = durationTime;
		this.createUser = createUser;
		this.createDate = createDate;
		this.updateUser = updateUser;
		this.updateDate = updateDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "airline_type")
	@Type(type = "airlinebooking.core.ws.enumtype.GenericEnumUserType", parameters = {
			@Parameter(name = "enumClass", value = "airlinebooking.core.ws.enumtype.AirlineType"),
			@Parameter(name = "identifierMethod", value = "getValue"),
			@Parameter(name = "valueOfMethod", value = "parseValue") })
	public AirlineType getAirlineType() {
		return this.airlineType;
	}

	public void setAirlineType(AirlineType airlineType) {
		this.airlineType = airlineType;
	}

	@Column(name = "flight_code", length = 100)
	public String getFlightCode() {
		return this.flightCode;
	}

	public void setFlightCode(String flightCode) {
		this.flightCode = flightCode;
	}

	@Column(name = "origin_code", length = 10)
	public String getOriginCode() {
		return this.originCode;
	}

	public void setOriginCode(String originCode) {
		this.originCode = originCode;
	}

	@Column(name = "destination_code", length = 10)
	public String getDestinationCode() {
		return this.destinationCode;
	}

	public void setDestinationCode(String destinationCode) {
		this.destinationCode = destinationCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "from_date", length = 10)
	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "to_date", length = 10)
	public Date getToDate() {
		return this.toDate;
	}

	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "from_time", length = 19)
	public Date getFromTime() {
		return this.fromTime;
	}

	public void setFromTime(Date fromTime) {
		this.fromTime = fromTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "to_time", length = 19)
	public Date getToTime() {
		return this.toTime;
	}

	public void setToTime(Date toTime) {
		this.toTime = toTime;
	}

	@Column(name = "duration_time")
	public Integer getDurationTime() {
		return this.durationTime;
	}

	public void setDurationTime(Integer durationTime) {
		this.durationTime = durationTime;
	}

	@Column(name = "create_user", length = 100)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "update_user", length = 100)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
